import { app, BrowserWindow, ipcMain, nativeTheme } from "electron";
import { FileApi } from "./handlers/file";
import { EngineFactory } from "./handlers/ai_engines/EngineFactory";
import { ImageApi } from "./handlers/Image";
import { ClipboardApi } from "./handlers/ClipboardApi";
import Store from "electron-store";
import { ApiKeyStorage } from "./handlers/ApiKeyStorage";
import "./autoupdate"

// This allows TypeScript to pick up the magic constants that's auto-generated by Forge's Webpack
// plugin that tells the Electron app where to look for the Webpack-bundled app code (depending on
// whether you're running in development or production).
declare const MAIN_WINDOW_WEBPACK_ENTRY: string;
declare const MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY: string;

// Handle creating/removing shortcuts on Windows when installing/uninstalling.
if (require("electron-squirrel-startup")) {
  app.quit();
}

const store = new Store();

const saveWindowBounds = (window: BrowserWindow): void => {
  const bounds = window.getBounds();
  store.set("windowSettings", bounds);
};

const createWindow = async (): Promise<void> => {
  const windowBounds = store.get("windowSettings") as
    | { width: number; height: number; x: number; y: number }
    | undefined;

  // Save window size and position on close

  // Create the browser window.
  const mainWindow = new BrowserWindow({
    height: windowBounds ? windowBounds.height : 600,
    width: windowBounds ? windowBounds.width : 800,
    x: windowBounds ? windowBounds.x : undefined,
    y: windowBounds ? windowBounds.y : undefined,
    minHeight: 600,
    minWidth: 800,
    webPreferences: {
      preload: MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY,
      devTools: process.env.NODE_ENV === "development",
    },
  });

  mainWindow.on("resize", () => {
    saveWindowBounds(mainWindow);
  });

  mainWindow.on("move", () => {
    saveWindowBounds(mainWindow);
  });

  // and load the index.html of the app.
  mainWindow.loadURL(MAIN_WINDOW_WEBPACK_ENTRY);

  // Open the DevTools.
  mainWindow.webContents.openDevTools();
};

let engine: AIEngine | null = null;

const createIpcHandlers = () => {
    
  ipcMain.handle("show-folder", (event, directoryPath: string) => {
    return FileApi.showFolder(directoryPath);
  });
  ipcMain.handle("read-file", (event, filePath) => FileApi.readFile(filePath));
  ipcMain.handle("select-directory", () => FileApi.selectDirectory());
  ipcMain.handle(
    "write-file-from-base64",
    (event, fileDirectory: string, fileName: string, data: string) => {
      return FileApi.writeFileFromBase64(fileDirectory, fileName, data);
    }
  );
  const apiKeyStorage = new ApiKeyStorage(store);

  ipcMain.handle("run-prompt", (event, engineName, prompt, modelsOptions, remixOptions) => {
    if (engineName !== engine?.engineName) {
      engine = EngineFactory.getEngine(engineName, apiKeyStorage);
      if (!engine) {
        throw new Error(`No API key found for engine: ${engineName}`);
      }
    }
    return EngineFactory.runPrompt(engine, event, prompt, modelsOptions, remixOptions);
  });
  ipcMain.handle("ai-stop-current-response", async (event, engineName) => {
    if (engineName !== engine?.engineName) {
      engine = EngineFactory.getEngine(engineName, apiKeyStorage);
      if (!engine) {
        throw new Error(`No API key found for engine: ${engineName}`);
      }
    }
    return await EngineFactory.stopCurrentResponse(engine);
  });
  ipcMain.handle("process-image", (event, imageData, imageOptions) => {
    return ImageApi.processImage(imageData, imageOptions);
  });
  ipcMain.handle("to-pixels", (event, imageData) => {
    return ImageApi.toPixels(imageData);
  });
  ipcMain.handle("from-pixels", (event, data, info) => {
    return ImageApi.fromPixels(data, info);
  });
  ipcMain.handle("clipboard-write-text", (event, text) => {
    return ClipboardApi.writeText(text);
  });
  ipcMain.handle("clipboard-read-text", () => {
    return ClipboardApi.readText();
  });

  // api key storage handlers
  ipcMain.handle("api-key-save", (event, service: string, apiKey: string) => {
    return apiKeyStorage.saveApiKey(service, apiKey);
  });
  ipcMain.handle("api-key-get", (event, service: string) => {
    return apiKeyStorage.getApiKey(service);
  });
  ipcMain.handle("api-key-delete", (event, service: string) => {
    engine = null;
    return apiKeyStorage.deleteApiKey(service);
  });

  // save and get settings handlers
  ipcMain.handle("settings-save", (event, settings: AppSettings) => {
    store.set("appSettings", settings);
  });
  ipcMain.handle("settings-get", () => {
    return store.get("appSettings");
  });

  return { apiKeyStorage };
}

const { apiKeyStorage } = createIpcHandlers();

// This method will be called when Electron has finished
// initialization and is ready to create browser windows.
// Some APIs can only be used after this event occurs.
app.whenReady().then(() => {
  app.setName("Pixel Image AI App");

  apiKeyStorage.initialize().then(() => {
    engine = EngineFactory.getEngine("openai", apiKeyStorage);
    console.log("API key storage initialized.");
    console.log("Engine initialized:", engine ? engine.engineName : "No engine");
  }).catch((err) => {
    console.error("Failed to initialize API key storage:", err);
  });

  nativeTheme.themeSource = "dark";

  createWindow();
});

// Quit when all windows are closed, except on macOS. There, it's common
// for applications and their menu bar to stay active until the user quits
// explicitly with Cmd + Q.
app.on("window-all-closed", () => {
  // if (process.platform !== 'darwin') {
  app.quit();
  // }
});

app.on("activate", () => {
  // On OS X it's common to re-create a window in the app when the
  // dock icon is clicked and there are no other windows open.
  if (BrowserWindow.getAllWindows().length === 0) {
    createWindow();
  }
});

// In this file you can include the rest of your app's specific main process
// code. You can also put them in separate files and import them here.
